version: "3"
services:
  beammp:
    image: "vagahbond/beammp_server"
    container_name: beammp
    ports:
      - "31853:30814/udp"
      - "31853:30814/tcp"
    networks:
      - beammp_net
    volumes:
      - ./Resources:/beammp/Resources
      # - ./Server.log:/beammp/Server.log
    environment:
      - PGID
      - PUID
      - TZ
      - Debug
      - Private
      - Port
      - MaxCars
      - MaxPlayers
      - Map
      - Name
      - Desc
      - use
      - AuthKey
      - Description
        #   restart: unless-stopped

networks:
  beammp_net:
